version: '3.4'
networks:
  proeventos:

services:
  db:
    container_name: dbcontainer
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=dockerflpslva2023
    networks:
      - proeventos

  api:
    container_name: apicontainer
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
       - 5000:80
       - 5001:443
    depends_on:
        - db
    environment:
        - DB_HOST=host.docker.internal
        - DB_NAME=ProEventos
        - DB_SA_PASSWORD=dockerflpslva2023
        - DB_PORT=1433
        - DB_USER=SA
    networks:
      - proeventos